contact_links:
  - name: Professional Support
    url: https://services.glpi-network.com/
    about: Professional support is available through GLPI Network subscription.
  - name: GLPI Community Support
    url: https://forum.glpi-project.org/
    about: You can ask questions and find answers on the forum.
  - name: GLPI project Telegram channel
    url: https://t.me/glpien
    about: A fast GLPI community support media.
