name: Feature request
description: Suggest an idea for this project
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: dropdown
    id: professional-support
    attributes:
      label: Professional support
      description: I know I can also request [professional services](https://services.glpi-network.com/) to develop such a feature.
      options:
        - Yes, I know
        - I still have but want a public following to inform the community
        - I'm a GLPI partner
        - I would like to be contacted
        - Still not applicable
    validations:
      required: false
  - type: textarea
    id: problem-related
    attributes:
      label: Is your feature request related to a problem?
      description: Please describe the problem if applicable.
      placeholder: There's always a problem when GLPI agent [...]
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you want to happen.
      placeholder: I would like [...]
    validations:
      required: true
  - type: textarea
    id: consideration
    attributes:
      label: Alternatives you've considered
      placeholder: A clear and concise description of alternative or feature you've considered to answer your need.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
